
"use strict";
(() => {
let db, mode="vista", page=1;
const main=document.getElementById("contenido");
document.querySelector(".skip").addEventListener("click",e=>{e.preventDefault();main.focus({preventScroll:true});main.scrollIntoView({block:"start"});});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=s=>String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const source=id=>db.sources.find(s=>s.id===id);
const cite=id=>{const s=source(id);return s?'<a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+' ↗</a>':"";};
const by=id=>document.getElementById(id);
const goAnchor=id=>{const el=by(id);if(el){el.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth",block:"start"});el.focus({preventScroll:true});}};
const art=()=>'<div class="art"><div class="art-caption"><span>Un mapa de curiosidades</span><span>Edición 01</span></div><svg viewBox="0 0 420 320" aria-hidden="true"><defs><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" fill="none" stroke="#bbc7b1" stroke-width=".6"/></pattern></defs><rect x="20" y="20" width="380" height="260" fill="url(#grid)"/><circle cx="206" cy="146" r="99" fill="#efd17d" opacity=".6"/><ellipse cx="206" cy="146" rx="140" ry="61" fill="none" stroke="#174c45" stroke-width="1.4" transform="rotate(-34 206 146)"/><ellipse cx="206" cy="146" rx="140" ry="61" fill="none" stroke="#174c45" stroke-width="1.4" transform="rotate(34 206 146)"/><path d="M89 236 201 36 327 240Z" fill="none" stroke="#174c45" stroke-width="1.7"/><path d="M56 146H359M206 22V284" stroke="#8f9e85" stroke-dasharray="4 6"/><circle cx="206" cy="146" r="6" fill="#174c45"/><circle cx="201" cy="36" r="4" fill="#174c45"/><circle cx="89" cy="236" r="4" fill="#174c45"/><circle cx="327" cy="240" r="4" fill="#174c45"/><text x="322" y="58" fill="#174c45" font-family="Georgia" font-size="22">ℚ</text><text x="40" y="247" fill="#174c45" font-family="Georgia" font-size="22">∞</text></svg><div class="art-label">Una pregunta abre muchos caminos.</div></div>';
function home(){
 main.innerHTML='<div class="wrap"><section class="hero"><div><span class="eyebrow"><span class="dot"></span>Una biblioteca para explorar juntos</span><h1>Las grandes preguntas también empiezan con <em>curiosidad.</em></h1><p class="intro">Acércate a las matemáticas sin tener que ser matemático. Descubre la historia, juega con las ideas y examina qué sabemos de cada propuesta de solución.</p><div class="actions"><a class="btn" href="#/001">Empezar por el 001 <span aria-hidden="true">↗</span></a><a class="text-link" href="#/catalogo">Recorrer la biblioteca →</a></div><p class="small" style="margin-top:18px">A tu ritmo. Con ejemplos, pistas y preguntas.</p></div>'+art()+'</section><div class="stats"><div class="stat"><strong>372</strong><span>familias de resultados en el catálogo</span></div><div class="stat"><strong>719</strong><span>manuscritos originales enlazados</span></div><div class="stat"><strong>001</strong><span>primer capítulo desarrollado</span></div></div><div class="section-label"><span class="eyebrow">Tu primera aventura</span></div><section class="pilot"><div class="big-number">001</div><div><span class="eyebrow">Teoría de números · Capítulo piloto</span><h2>Una geometría,<br>muchas formas de leerla.</h2><p>¿Pueden distintos métodos reconocer la misma fracción? Entramos en la conjetura de racionalidad de Milne.</p><span class="small">Primer vistazo: 3–5 min · Recorrido: 20–30 min</span></div><div class="actions"><a class="btn" href="#/001">Abrir el capítulo ↗</a></div></section><div class="triad"><article><div class="number">01</div><h3>Comprender la pregunta</h3><p>Una entrada sencilla, los conceptos necesarios y la historia de quienes intentaron responderla.</p></article><article><div class="number">02</div><h3>Experimentar con las ideas</h3><p>Cambia números, haz una predicción y descubre qué ocurre. Cada actividad explica hasta dónde llega su analogía.</p></article><article><div class="number">03</div><h3>Mirar con atención</h3><p>Separamos lo que afirma el manuscrito de las revisiones y comprobaciones disponibles.</p></article></div><p class="small">La biblioteca está en crecimiento: 1 capítulo desarrollado y 371 familias pendientes. Una ficha editorial completa no significa que hayamos certificado una demostración.</p></div>';
}
function catalog(){
 page=1;const areas=[...new Set(db.catalog.entries.map(e=>e.area))].sort((a,b)=>a.localeCompare(b,"es"));
 main.innerHTML='<div class="wrap"><div class="page-top"><span class="eyebrow">Biblioteca · Versión registrada</span><h1>Un universo de preguntas.<br>Un capítulo a la vez.</h1><p class="intro">372 familias agrupan 719 manuscritos. Conservamos los títulos originales y la numeración del catálogo; los saltos entre identificadores son parte de la fuente.</p><p class="small">Las áreas están traducidas al español. «Desarrollado» describe el avance educativo, no la validez matemática de una propuesta.</p></div><form id="filters" class="filters" role="search"><label>Buscar por título o número<input id="search" type="search" placeholder="Por ejemplo: 001, Milne, geometry" autocomplete="off"></label><label>Área<select id="area"><option value="">Todas las áreas</option>'+areas.map(a=>'<option>'+esc(a)+'</option>').join("")+'</select></label><label>Avance editorial<select id="status"><option value="">Todos</option><option>Desarrollado</option><option>Pendiente</option></select></label></form><div class="results-line"><span id="result-count" role="status"></span><span>Fecha de corte: 8 octubre 2026 · <a href="'+esc(db.catalog.entries[0].source)+'" target="_blank" rel="noopener">Catálogo original ↗</a></span></div><div id="catalog-cards" class="catalog-grid"></div><div id="pagination" class="pagination"></div></div>';
 by("filters").addEventListener("submit",e=>e.preventDefault());
 ["search","area","status"].forEach(id=>by(id).addEventListener(id==="search"?"input":"change",()=>{page=1;cards();}));
 cards();
}
function cards(){
 const q=norm(by("search").value.trim()),area=by("area").value,status=by("status").value;
 const entries=db.catalog.entries.filter(e=>(!q||norm(e.id+" "+e.title+" "+e.papers.map(p=>p.title).join(" ")+" "+(e.id==="001"?"Milne racionalidad especialización algebraica":"")).includes(q))&&(!area||e.area===area)&&(!status||e.status===status));
 const size=24,total=Math.max(1,Math.ceil(entries.length/size));page=Math.min(page,total);
 by("result-count").textContent=entries.length+" "+(entries.length===1?"familia":"familias")+" · "+entries.reduce((s,e)=>s+e.papers.length,0)+" "+(entries.reduce((s,e)=>s+e.papers.length,0)===1?"manuscrito":"manuscritos");
 by("catalog-cards").innerHTML=entries.length?entries.slice((page-1)*size,page*size).map(e=>'<article class="catalog-card"><div class="card-top"><span class="card-number">'+esc(e.id)+'</span><span class="badge '+(e.id==="001"?"ready":"")+'">'+esc(e.status)+'</span></div><h2>'+esc(e.title)+'</h2><p class="small">'+esc(e.area)+' · '+e.papers.length+' '+(e.papers.length===1?"manuscrito":"manuscritos")+'</p>'+(e.id==="001"?'<p><a class="btn" href="#/001">Explorar en español ↗</a></p>':"")+'<details><summary>Ver manuscritos del '+esc(e.id)+'</summary>'+(e.id!=="001"?'<p class="small" style="margin-top:15px">Capítulo educativo pendiente. Estos enlaces llevan al material original, cuyo respaldo aún no hemos estudiado aquí.</p>':"")+'<ul class="paper-list">'+e.papers.map(p=>'<li><a href="'+esc(p.url)+'" target="_blank" rel="noopener">'+esc(p.title)+' ↗</a></li>').join("")+'</ul></details></article>').join(""):'<p class="empty">No hay coincidencias. Prueba con otro título o cambia los filtros.</p>';
 by("pagination").innerHTML='<button id="prev" '+(page===1?"disabled":"")+'>← Anterior</button><span>Página '+page+' de '+total+'</span><button id="next" '+(page===total?"disabled":"")+'>Siguiente →</button>';
 [["prev",-1],["next",1]].forEach(([id,delta])=>by(id).addEventListener("click",()=>{page+=delta;cards();by("result-count").scrollIntoView({block:"center"});by(delta<0?"prev":"next").focus({preventScroll:true});}));
}
function lesson(){
 const l=db.lesson;
 main.innerHTML='<div class="wrap"><div class="lesson-hero"><div class="breadcrumb"><a href="#/catalogo">Biblioteca</a><span aria-hidden="true">/</span><span>001</span></div><span class="eyebrow">001 · '+esc(l.area)+' · Capítulo piloto</span><h1>'+esc(l.title)+'</h1><p class="intro">'+esc(l.subtitle)+'</p><p class="formal-title">'+esc(l.formalTitle)+'</p><div class="lesson-meta"><span class="badge ready">Edición educativa completa</span><span class="badge">Evaluación provisional</span><span class="badge">Fuente: 7 octubre 2026</span></div><div class="modes" role="group" aria-label="Profundidad de lectura"><button data-mode="vista" aria-pressed="'+(mode==="vista")+'">Primer vistazo · 3–5 min</button><button data-mode="recorrido" aria-pressed="'+(mode==="recorrido")+'">Recorrido · 20–30 min</button><button data-mode="profundo" aria-pressed="'+(mode==="profundo")+'">Ampliación opcional</button></div><p class="mode-note" id="mode-note"></p></div><div class="lesson-layout"><aside class="toc" aria-label="En este capítulo"><span class="eyebrow">En este capítulo</span><ol id="toc"></ol><p class="small">La actividad ilustra ideas. La demostración está en el manuscrito.</p><a href="#/glosario">Abrir el glosario →</a></aside><div class="lesson-body"><div id="quick" class="recap"><h2>La pregunta en una mirada</h2><p>Una misma clase geométrica puede estudiarse mediante distintas cohomologías. Milne preguntó si ciertos emparejamientos con divisores de la reducción provienen de un mismo número racional.</p><p>OpenAI afirma probarlo. Una consecuencia adicional de especialización algebraica utiliza también el resultado 032. La prueba principal de racionalidad no depende de él.</p><p>Milne comentó favorablemente el anuncio. Nuestra revisión educativa todavía no equivale a una auditoría completa ni a una comprobación formal reproducida.</p><button id="start-tour" class="btn secondary" style="background:var(--gold)">Entrar al recorrido →</button></div>'+l.sections.map(s=>'<section id="'+esc(s.id)+'" class="chapter-section" tabindex="-1"><span class="eyebrow">'+esc(s.kicker)+'</span><h2>'+esc(s.title)+'</h2>'+s.html+'</section>').join("")+'<div class="section-end"><a class="btn secondary" href="#/metodo">Cómo investigamos →</a> <a class="text-link" href="#/fuentes">Consultar las fuentes ↗</a></div></div></div></div>';
 document.querySelectorAll("[data-mode]").forEach(b=>b.addEventListener("click",()=>{mode=b.dataset.mode;setMode();}));
 by("start-tour").addEventListener("click",()=>{mode="recorrido";setMode();goAnchor("conceptos");});
 by("timeline").innerHTML=l.timeline.map(t=>'<article><time>'+esc(t.year)+'</time><h3>'+esc(t.title)+'</h3><p>'+esc(t.text)+'</p><div class="source-note">'+cite(t.source)+'</div></article>').join("");
 labs();proof();quizzes();setMode();
}
function setMode(){
 const quick=mode==="vista";
 by("quick").hidden=!quick;
 document.querySelectorAll("[data-mode]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.mode===mode)));
 const visible=db.lesson.sections.filter(s=>!quick||s.id==="pregunta");
 db.lesson.sections.forEach(s=>{by(s.id).hidden=!visible.includes(s);});
 by("toc").innerHTML=visible.map(s=>'<li><a href="#/001/'+s.id+'" data-anchor="'+s.id+'">'+esc(s.title)+'</a></li>').join("");
 by("toc").querySelectorAll("a").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();goAnchor(a.dataset.anchor);}));
 by("mode-note").textContent=quick?"La idea central y sus límites. Cuando quieras, abre el recorrido completo.":mode==="recorrido"?"Nueve paradas, dos experimentos y tres retos. Las notas técnicas se abren solo si te interesan.":"El mismo recorrido, con las notas técnicas abiertas y enlaces para profundizar.";
 document.querySelectorAll("details.technical").forEach(d=>d.open=mode==="profundo");
}
function labs(){
 by("mod-lab").innerHTML='<div class="lab"><span class="eyebrow">Experimento 1 · Un reloj aritmético</span><h3>¿Qué cambia cuando vuelves al cero?</h3><p>Predice el resto antes de cambiar el número. ¿Qué pasará si le sumas exactamente una vuelta?</p><div class="lab-grid"><div class="lab-controls"><label>Número entero n (0 a 100)<input id="mod-n" type="number" min="0" max="100" step="1" value="12"></label><label>Número de posiciones p<select id="mod-p"><option>2</option><option>3</option><option selected>5</option><option>7</option><option>11</option></select></label><button id="add-p">Sumar una vuelta (+p)</button><div id="mod-result" class="result" role="status"></div></div><div id="mod-clock"></div></div><p class="small">Relación con el 001: introduce la característica p. Límite: no representa variedades, cohomología ni la prueba de racionalidad.</p></div>';
 const update=()=>{
 const raw=by("mod-n").value,n=Number(raw),p=Number(by("mod-p").value);
 if(raw===""||!Number.isInteger(n)||n<0||n>100){by("mod-result").textContent="Escribe un entero entre 0 y 100.";by("add-p").disabled=true;return;}
 by("add-p").disabled=n+p>100;
 const r=n%p,q=Math.floor(n/p);
 by("mod-result").innerHTML='<strong>'+n+' = '+q+' × '+p+' + '+r+'</strong><br>En este reloj, '+n+' y '+r+' quedan en la misma posición.<br>'+p+' sumas de 1 dan 0 módulo '+p+'.';
 const nodes=Array.from({length:p},(_,i)=>{const a=i*2*Math.PI/p-Math.PI/2,x=130+85*Math.cos(a),y=130+85*Math.sin(a);return '<circle cx="'+x+'" cy="'+y+'" r="17" fill="'+(i===r?"#174c45":"#eaf0e8")+'" stroke="#174c45"/><text x="'+x+'" y="'+(y+5)+'" text-anchor="middle" font-size="15" fill="'+(i===r?"white":"#174c45")+'">'+i+'</text>';}).join("");
 by("mod-clock").innerHTML='<svg role="img" aria-label="Reloj de '+p+' posiciones: el resto de '+n+' es '+r+'" viewBox="0 0 260 260"><circle cx="130" cy="130" r="85" fill="none" stroke="#bbcbb9" stroke-width="2"/>'+nodes+'<text x="130" y="127" text-anchor="middle" fill="#174c45" font-family="Georgia" font-size="28">mod '+p+'</text><text x="130" y="153" text-anchor="middle" fill="#586b65" font-size="12">resto: '+r+'</text></svg>';
 };
 by("mod-n").addEventListener("input",update);by("mod-p").addEventListener("change",update);
 by("add-p").addEventListener("click",()=>{by("mod-n").value=Number(by("mod-n").value)+Number(by("mod-p").value);update();});update();
 by("ratio-lab").innerHTML='<div class="lab"><span class="eyebrow">Experimento 2 · El mismo número, otra escritura</span><h3>Una fracción no siempre termina en el decimal.</h3><p>Elige una fracción. ¿Su forma decimal te dice de inmediato cuál es su valor exacto?</p><div class="lab-grid"><div><label>Numerador a (0 a 30)<input id="ratio-a" type="number" min="0" max="30" step="1" value="1"></label><label style="margin-top:15px">Denominador b (1 a 20)<input id="ratio-b" type="number" min="1" max="20" step="1" value="3"></label></div><div><div id="ratio-result" role="status" class="result"></div></div></div><p class="small">Relación con el 001: un valor racional puede tener varias representaciones. Límite: aquí cambiamos la escritura de una fracción; no comparamos las realizaciones cohomológicas del teorema.</p></div>';
 const ratio=()=>{const ar=by("ratio-a").value,br=by("ratio-b").value,a=Number(ar),b=Number(br);
 if(ar===""||br===""||!Number.isInteger(a)||!Number.isInteger(b)||a<0||a>30||b<1||b>20){by("ratio-result").textContent="Usa enteros: a entre 0 y 30; b entre 1 y 20.";return;}
 let x=a,y=b;while(y){[x,y]=[y,x%y];}const g=x||1;
 let den=b/g;while(den%2===0)den/=2;while(den%5===0)den/=5;
 by("ratio-result").innerHTML='<span class="small">Fracción exacta simplificada</span><output>'+a/g+' / '+b/g+'</output><span class="small">Decimal mostrado a seis cifras</span><output>≈ '+(a/b).toFixed(6).replace(".",",")+'</output><p>'+ (den===1?"Esta fracción tiene un decimal finito. La cifra mostrada puede estar redondeada.":"Su decimal es periódico: no termina. Mostrar seis cifras es una aproximación.")+'</p>';};
 ["ratio-a","ratio-b"].forEach(id=>by(id).addEventListener("input",ratio));ratio();
}
function proof(){
 const p=db.lesson.proof;
 by("proof-map").innerHTML='<div class="proof-map"><span class="eyebrow">Selecciona una etapa</span><svg viewBox="0 0 600 100" role="img" aria-label="Cuatro etapas del argumento, conectadas en orden"><path d="M65 40H535" stroke="#9aaf9a" stroke-width="2"/>'+p.map((s,i)=>'<circle cx="'+(65+i*157)+'" cy="40" r="22" fill="#174c45"/><text x="'+(65+i*157)+'" y="47" fill="white" text-anchor="middle" font-family="Georgia" font-size="21">'+(i+1)+'</text>').join("")+'</svg><div class="proof-buttons">'+p.map((s,i)=>'<button data-step="'+i+'" aria-pressed="'+(i===0)+'">Etapa '+(i+1)+'</button>').join("")+'</div><div id="proof-detail" class="proof-detail" aria-live="polite"></div><details class="dependency"><summary>Dependencia 032 · Solo para la consecuencia algebraica</summary><p>La racionalidad es el resultado principal del 001. Para deducir especialización algebraica, el manuscrito utiliza además el teorema de Hodge para variedades abelianas CM del 032. La consecuencia hereda esa dependencia. Aquí no auditamos ni desarrollamos el 032.</p><p>'+cite("final")+'</p><a href="'+esc(db.catalog.entries.find(e=>e.id==="032").papers[0].url)+'" target="_blank" rel="noopener">Ver el manuscrito asociado al 032 ↗</a></details></div>';
 const show=i=>{const s=p[i];by("proof-detail").innerHTML='<h3>'+esc(s.title)+'</h3><p>'+esc(s.text)+'</p><p class="source-note"><strong>Punto para la revisión:</strong> '+esc(s.audit)+'</p><p class="source-note">'+cite(s.source)+'</p>';document.querySelectorAll("[data-step]").forEach(b=>b.setAttribute("aria-pressed",String(Number(b.dataset.step)===i)));};
 document.querySelectorAll("[data-step]").forEach(b=>b.addEventListener("click",()=>show(Number(b.dataset.step))));show(0);
}
function quizzes(){
 by("quiz").innerHTML=db.lesson.quizzes.map((q,i)=>'<article class="quiz-card"><fieldset><legend>Reto '+(i+1)+' · '+esc(q.question)+'</legend>'+q.answers.map((a,j)=>'<label class="quiz-option"><input type="radio" name="quiz-'+i+'" value="'+j+'"><span>'+esc(a)+'</span></label>').join("")+'</fieldset><div class="quiz-tools"><button data-check="'+i+'">Comprobar mi respuesta</button><details><summary>Una pista</summary><p>'+esc(q.hint)+'</p></details></div><div id="feedback-'+i+'" class="feedback" role="status"></div></article>').join("");
 document.querySelectorAll("[data-check]").forEach(b=>b.addEventListener("click",()=>{const i=Number(b.dataset.check),q=db.lesson.quizzes[i],selected=document.querySelector('input[name="quiz-'+i+'"]:checked');by("feedback-"+i).innerHTML=selected?'<strong>'+(Number(selected.value)===q.correct?"Esa es la idea.":"Volvamos a mirarlo.")+'</strong> '+esc(q.explanation):"Elige una respuesta o abre la pista. Puedes intentarlo las veces que quieras."; }));
}
function glossary(){
 main.innerHTML='<div class="wrap"><div class="page-top"><span class="eyebrow">Herramientas para comprender</span><h1>Un glosario sin apuro.</h1><p class="intro">Abre solo las palabras que necesites. Cada definición incluye un límite para que el ejemplo no nos lleve a una conclusión equivocada.</p></div><label class="glossary-search">Buscar un concepto<input id="glossary-search" type="search" placeholder="Racional, Hodge, divisor…"></label><div id="glossary-count" role="status" class="small"></div><div id="glossary-list" class="glossary-list"></div></div>';
 const show=()=>{const entries=db.glossary.filter(g=>norm(g.term+" "+g.definition).includes(norm(by("glossary-search").value)));by("glossary-count").textContent=entries.length+" conceptos";
 by("glossary-list").innerHTML=entries.length?entries.map(g=>'<details><summary>'+esc(g.term)+'</summary><p>'+esc(g.definition)+'</p><p class="limit"><strong>Hasta dónde llega:</strong> '+esc(g.limit)+'</p><p class="source-note">'+cite(g.source)+'</p></details>').join(""):'<p>No encontramos ese concepto. Prueba una palabra más corta.</p>';};
 by("glossary-search").addEventListener("input",show);show();
}
function methodology(){
 const m=db.method;
 main.innerHTML='<div class="wrap"><div class="page-top"><span class="eyebrow">Método · Evidencia · Correcciones</span><h1>Curiosidad y rigor,<br>en el mismo recorrido.</h1><p class="intro">Esta biblioteca enseña a comprender y contrastar propuestas. No promete certificar demostraciones como una revisión matemática especializada.</p></div><div class="prose"><h2>Un proceso que podemos repetir</h2><ol class="method-steps">'+m.steps.map(([t,p])=>'<li><h3>'+esc(t)+'</h3><p>'+esc(p)+'</p></li>').join("")+'</ol><h2>Cuatro preguntas distintas</h2><div class="evidence-grid">'+m.criteria.map(([t,p])=>'<article><h3>'+esc(t)+'</h3><p>'+esc(p)+'</p></article>').join("")+'</div><div class="analogy"><strong>Un experimento no es una demostración.</strong><p>Una actividad puede mostrar una regla, una intuición o una limitación. Cada capítulo dirá qué relación tiene con el problema y qué aspectos no representa.</p></div><h2>Avance editorial y respaldo</h2><p>«Pendiente» significa que la familia aún no tiene capítulo educativo. «Desarrollado» significa que completamos la narración, las actividades, las fuentes y una revisión provisional. Estos estados no expresan aceptación de un teorema por la comunidad.</p><p>Los títulos del catálogo son los originales. Un conjunto de artículos relacionados cuenta como una familia; no renumeramos los identificadores ni rellenamos los huecos.</p><h2>Qué revisamos en el piloto</h2><p>'+esc(m.search)+'</p><p>Leímos el texto fuente completo del 001 y reconstruimos su arquitectura. No reproducimos cada argumento de sus referencias, no ejecutamos Lean y no auditamos el 032. La nota favorable de Milne se presenta con fecha y alcance.</p><p class="source-note">'+cite("lean")+' · '+cite("comparator")+' · '+cite("reaccion")+'</p><h2>Preguntas que quedan abiertas</h2><ul>'+m.questions.map(q=>'<li>'+esc(q)+'</li>').join("")+'</ul><h2>Registro de correcciones</h2>'+m.corrections.map(c=>'<p><strong>'+esc(c.date)+':</strong> '+esc(c.text)+'</p>').join("")+'<p>Para señalar un error, abre una <a href="https://github.com/JFR-DEV/explorador-matematico/issues" target="_blank" rel="noopener">incidencia en el repositorio ↗</a> indicando el capítulo, la afirmación y la fuente. Las nuevas revisiones se registrarán con fecha y versión; no hay actualizaciones automáticas en esta edición.</p><h2>Continuar en orden</h2><p>Primero recorreremos juntos el 001 y ajustaremos el piloto con tus preguntas. Después abordaremos el 002. Cada familia tendrá una ficha con fuentes, dependencias, estado editorial y dudas pendientes.</p><p class="snapshot">Versión original estudiada: <code>'+esc(m.sourceCommit)+'</code><br>Fecha de corte: 8 de octubre de 2026. Solo el 001 está desarrollado.</p><a class="btn" href="#/001">Volver al capítulo piloto ↗</a></div></div>';
}
function sources(){
 main.innerHTML='<div class="wrap"><div class="page-top"><span class="eyebrow">Referencias verificables</span><h1>La biblioteca también<br>se puede mirar por dentro.</h1><p class="intro">Fuentes de la primera edición, con una nota sobre su alcance. Los manuscritos se enlazan a la versión estudiada de tu copia del repositorio.</p></div><div class="prose"><p class="snapshot">Fecha de consulta: 8 de octubre de 2026.<br>Versión original: <code>'+esc(db.catalog.version)+'</code></p><ul class="source-list">'+db.sources.map(s=>'<li id="fuente-'+esc(s.id)+'"><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+' ↗</a><p>'+esc(s.note)+'</p></li>').join("")+'</ul><p class="small">Esta biblioteca es un proyecto educativo independiente. No representa una revisión oficial de OpenAI ni de los autores citados.</p></div></div>';
}
function route(){
 const [name,anchor]=(location.hash.replace(/^#\/?/,"")||"inicio").split("/");
 const routes={inicio:home,catalogo:catalog,"001":lesson,glosario:glossary,metodo:methodology,fuentes:sources};
 (routes[name]||home)();
 const titles={inicio:"Inicio",catalogo:"Biblioteca", "001":"001 · Conjetura de racionalidad de Milne",glosario:"Glosario",metodo:"Cómo investigamos",fuentes:"Fuentes"};
 document.title=(titles[name]||titles.inicio)+" · Explorador matemático";
 document.querySelectorAll(".header-inner nav a").forEach(a=>{if(a.getAttribute("href")==="#/"+name)a.setAttribute("aria-current","page");else a.removeAttribute("aria-current");});
 window.scrollTo(0,0);main.focus({preventScroll:true});
 if(name==="001"&&anchor&&db.lesson.sections.some(s=>s.id===anchor)){mode="recorrido";setMode();goAnchor(anchor);}
}
Promise.all(["catalog","001","glossary","sources","method"].map(async n=>{const r=await fetch("./data/"+n+".json");if(!r.ok)throw Error("No pudimos cargar "+n);return r.json();}))
 .then(([catalog,lesson,glossary,sources,method])=>{db={catalog,lesson,glossary,sources,method};route();window.addEventListener("hashchange",route);})
 .catch(()=>{main.innerHTML='<div class="wrap error"><h1>No pudimos cargar la biblioteca.</h1><p>Comprueba tu conexión y recarga la página. Puedes consultar los contenidos en el repositorio mientras tanto.</p><a href="https://github.com/JFR-DEV/explorador-matematico/tree/main/data">Abrir los contenidos en GitHub ↗</a></div>';});
})();
